from app.api.health import api_bp
from app.auth.routes import auth_bp
from app.resumes.routes import resumes_bp
from app.api.candidates import candidates_bp
from app.api.jobs import jobs_bp
from app.api.matching import matching_bp
from app.api.applications import applications_bp
from app.api.search import search_bp
from app.api.analytics import analytics_bp
